version: '3.8'
services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./notebooks/mlruns:/app/notebooks/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///app/notebooks/mlruns
    restart: unless-stopped
